name: kerykeion_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  sweph:
    path: ../../sweph_local
  timezone: ">=0.10.0 <1.0.0"
  # path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.26.3
  mcp_dart:
    path: ../../saju_chat/mcp_dart
  http: ^1.4.0
#  test: ^1.25.6  # flutter_test replaces test

flutter:

